### ISSUE TITLE
Add install instructions to README

### ISSUE THREAD

**Issue by ddaws** [ldo/blendgit#1]
It would be great if there were install instruction in the README. Alternatively links to instructions on installing would also be helpful.

**Comment by ldo** [comment]
The installation instructions are the same for any addon: just copy it to your ~/.config/blender/_version_/scripts/addons/ directory.

**Comment by ddaws** [comment]
I am running blender on Mac and do not have a `~/.config/blender` directory. Could you link me instructions or doc explaining alternative installation locations please and thanks?

**Comment by ldo** [comment]
Sorry, I do not have a Mac running OS X to test with.

Use Blender’s built-in addon installation function.
