### ISSUE TITLE
Not being able to make it work

### ISSUE THREAD

**Issue by JorgeDePedroCG** [ldo/blendgit#3]
I´m currently using Blender 2.79 and I have tried to install the add-on from the User Preferences, but no new add-on appears on the list, and no new sub-menus appear on the File menu.  A little more info on how to run this, would be useful. 

I´ve selected the zip file to install the add on, it did nothing. If unzipping and selecting the blendgit.py file from UserPreferences > Addons, it will complain about not finding the __init__.py file.

**Comment by ldo** [comment]
You just copy `blendgit.py` to `~/.config/blender/`*version*`/scripts/addons/`. To be safe, quit and restart Blender. The addon should appear in the "System” section -- or search for “git”.

**Comment by JorgeDePedroCG** [comment]
Fab, the menu shows up now. 

But now when saving version, I´m getting an error.  I have previously saved the file. 

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\blendgit.py", line 212, in execute
    setup_workdir()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\blendgit.py", line 95, in setup_workdir
    os.symlink("../" + os.path.basename(get_repo_name()), os.path.join(work_dir, ".git"))
OSError: symbolic link privilege not held

location: <unknown location>:-1
```

**Comment by ldo** [comment]
No idea about Windows, sorry. Try [this guy](https://github.com/kevinzhow/blendgit).
