### ISSUE TITLE
2.80 compatibility

### ISSUE THREAD

**Issue by Strandbummler** [ldo/blendgit#5]
Will you update this addon to make it work with 2.80?

Kind regards

**Comment by ldo** [comment]
Yes, that sounds like a good idea. I’m not sure if the 2.8 Python API has stabilized yet.

**Comment by cjacket** [comment]
According to the blender.org site the API should be mostly stabilized with minimal changes at this point.
[Python API 2.8 release notes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API)

**Comment by rdcklinux** [comment]
Blener 2.80 is stable now!!

**Comment by ldo** [comment]
This was done a [while back](https://github.com/ldo/blendgit/commit/2988052c312871a0a821b94a18890d42c341a7a9).
